services:
  chrome-server:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"

  automation:
    build: .
    depends_on:
      - chrome-server
    environment:
      - SE_REMOTE_URL=http://chrome-server:4444
    volumes:
      - ./:/app                # Map local project to /app inside container